### ISSUE TITLE
默认用户名和密码没有提供呀

### ISSUE THREAD

**Issue by DrewZt** [leeboby/openkylin-images#1]

**Comment by leeboby** [comment]
https://docs.openkylin.top/zh/%E7%A4%BE%E5%8C%BA%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/arm%E4%B8%8A%E5%AE%89%E8%A3%85openKylin

**Comment by wellexp** [comment]
> https://docs.openkylin.top/zh/%E7%A4%BE%E5%8C%BA%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/arm%E4%B8%8A%E5%AE%89%E8%A3%85openKylin

链接打不开，还是不知道密码是多少…

**Comment by leeboby** [comment]
是没有提供默认密码，登录桌面后自己设置一个密码就行了。

为什么不提供默认密码，因为OpenKylin官方系统默认就是这样的。

《OpenKylin ARM使用参考文档》是链接到OpenKylin官方文档的，也已经失效了。
