### ISSUE TITLE
《OpenKylin ARM使用参考文档》文档链接打不开

### ISSUE THREAD

**Issue by wellexp** [leeboby/openkylin-images#2]
没有提供默认密码，《OpenKylin ARM使用参考文档》链接打不开，没有密码无法更改系统设置，系统时区和时间错误；锁屏后需要密码解锁

**Comment by leeboby** [comment]
是没有提供默认密码，登录桌面后自己设置一个密码就行了。

为什么不提供默认密码，因为OpenKylin官方系统默认就是这样的。

《OpenKylin ARM使用参考文档》是链接到OpenKylin官方文档的，也已经失效了。
